export const items =  [
    {
      id: 1,
      category: 'mobiles',
      title: "Apple iPhone 14",
      imgSrc: 'https://m.media-amazon.com/images/I/61bK6PMOC3L._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Apple iPhone 14 (128 GB) - Blue',
      price: '69,999',
    },

    {
      id:10,
      category: 'mobiles',
      title: "Samsung Galaxy S24",
      imgSrc:' https://m.media-amazon.com/images/I/41OmEIOlJCL._SX300_SY300_QL70_FMwebp_.jpg',
      amazonLink: 'https://t.ly/45NC3',
      description: 'Samsung Galaxy S24 5G AI Smartphone (Onyx Black, 8GB, 256GB Storage)',
      price: '67,999',
    },

    {
      id: 5,
      category: 'laptops',
      title: "Xiaomi [Smartchoice] Notebookpro",
      imgSrc: 'https://m.media-amazon.com/images/I/41Ix2JelnmL._SX300_SY300_QL70_FMwebp_.jpg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Xiaomi [Smartchoice] Notebookpro ',
      price: '49,999',
    },

    {
      id: 7,
      category: 'tablets',
      title: "Xiaomi Pad 6",
      imgSrc: 'https://m.media-amazon.com/images/I/415gV21fNCL._SX300_SY300_QL70_FMwebp_.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Xiaomi Pad 6| Qualcomm Snapdragon 870| ',
      price: '24,999',
    },
    {
      id: 2,
      category: 'mobiles',
      title: "Apple iPhone 15 Pro Max",
      imgSrc: 'https://m.media-amazon.com/images/I/41zb7hwFUmL._SY445_SX342_QL70_FMwebp_.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Apple iPhone 15 Pro Max (512GB) - Black',
      price: '44,999',
    },
    {
      id: 6,
      category: 'tablets',
      title: "Lenovo Tab P12 Pro",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB, Wi-fi Only), Storm Grey with Precision Pen 3',
      price: '19,999',
    },
    {
      id: 3,
      category: 'mobiles',
      title: "Apple iPhone 13",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 13 (128GB) - Blue',
      price: '59,999',
    },

    {
      id: 4,
      category: 'laptops',
      title: "Lenovo IdeaPad Slim 5 ",
      imgSrc: 'https://www.nehruplacedealers.com/wp-content/uploads/2023/03/Lenovo-IdeaPad-Slim-5-Core-i5.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm) ',
      price: '29,999',
    },
    {
      id: 9,
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      imgSrc: 'https://m.media-amazon.com/images/I/41cahbke2QL._SY300_SX300_QL70_FMwebp_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Gray, (SM-X200NZAEINU)',
      price: '39,999',
    },
    {
      id: 8,
      category: 'laptops',
      title: "Apple MacBook Air Laptop",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
      price: '99,999',
    },

    {
      id:11,
      category: ' mobiles',
      title: "Samsung Galacy S24 Ultra",
      imgSrc: 'https://images-eu.ssl-images-amazon.com/images/I/71RVuBs3q9L._AC_UL232_SR232,232_.jpg',
      amazonLink:'https://t.ly/xxGM1',
      description:'Samsung Galaxy S24 Ultra 5G AI Smartphone (Titanium Black, 12GB, 512GB Storage)',
      price:'1,39,999',
    },

    {
      id:12,
      category:'laptops',
      title:"HONOR MagicBook X16 Pro",
      imgSrc: 'https://m.media-amazon.com/images/I/31VjFTkNt3L._AC_.jpg',
      amazonLink:'https://t.ly/FBe9r',
      description:'HONOR MagicBook X16 Pro 2024, 13th Gen Intel Core i5-13420H (16GB/512GB NVMe SSD, 16-inch /Windows 11/Backlit Keyboard/Fingerprint/1.75Kg)',
      price: '51,999' ,
    },

  
  ]